//
//  Gauges.swift
//  GasLaw
//
//  Created by Szabolcs Toth on 2021. 11. 06..
//  Copyright © 2021 . All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import Cocoa

public class Gauges : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawPressure(frame targetFrame: NSRect = NSRect(x: 0, y: 0, width: 200, height: 200), resizing: ResizingBehavior = .aspectFit, pressureValue: CGFloat = 0) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext
        
        //// Resize to Target Frame
        NSGraphicsContext.saveGraphicsState()
        let resizedFrame: NSRect = resizing.apply(rect: NSRect(x: 0, y: 0, width: 200, height: 200), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 200, y: resizedFrame.height / 200)
        let resizedShadowScale: CGFloat = min(resizedFrame.width / 200, resizedFrame.height / 200)


        //// Color Declarations
        let strokeColor5 = NSColor(red: 1, green: 1, blue: 1, alpha: 1)
        let fillColor3 = NSColor(red: 0.969, green: 0.969, blue: 0.969, alpha: 1)
        let strokeColor8 = NSColor(red: 0.286, green: 0.318, blue: 0.349, alpha: 1)
        let fillColor4 = NSColor(red: 0.886, green: 0.886, blue: 0.886, alpha: 1)
        let strokeColor9 = NSColor(red: 0.984, green: 0.733, blue: 0.082, alpha: 0.5)
        let strokeColor10 = NSColor(red: 0.173, green: 0.761, blue: 0.408, alpha: 0.5)
        let strokeColor11 = NSColor(red: 0.984, green: 0.082, blue: 0.082, alpha: 0.6)
        let fillColor5 = NSColor(red: 0.2, green: 0.2, blue: 0.2, alpha: 1)

        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = NSColor.black.withAlphaComponent(0.1)
        shadow.shadowOffset = NSSize(width: 3, height: -3)
        shadow.shadowBlurRadius = 5

        //// Pressure Gauge
        //// Oval Drawing
        let ovalPath = NSBezierPath(ovalIn: NSRect(x: 30, y: 30, width: 140, height: 140))
        fillColor4.setFill()
        ovalPath.fill()
        strokeColor8.setStroke()
        ovalPath.lineWidth = 10
        ovalPath.stroke()


        //// Bezier Drawing
        let bezierPath = NSBezierPath()
        bezierPath.move(to: NSPoint(x: 68.63, y: 58.74))
        bezierPath.curve(to: NSPoint(x: 50.49, y: 84.63), controlPoint1: NSPoint(x: 60.04, y: 65.28), controlPoint2: NSPoint(x: 53.7, y: 74.33))
        bezierPath.curve(to: NSPoint(x: 50.69, y: 116.25), controlPoint1: NSPoint(x: 47.27, y: 94.93), controlPoint2: NSPoint(x: 47.34, y: 105.98))
        bezierPath.curve(to: NSPoint(x: 69.17, y: 141.9), controlPoint1: NSPoint(x: 54.04, y: 126.51), controlPoint2: NSPoint(x: 60.5, y: 135.47))
        bezierPath.curve(to: NSPoint(x: 99.1, y: 152.11), controlPoint1: NSPoint(x: 77.85, y: 148.33), controlPoint2: NSPoint(x: 88.3, y: 151.89))
        bezierPath.curve(to: NSPoint(x: 129.4, y: 143.09), controlPoint1: NSPoint(x: 109.89, y: 152.32), controlPoint2: NSPoint(x: 120.48, y: 149.17))
        bezierPath.curve(to: NSPoint(x: 148.89, y: 118.2), controlPoint1: NSPoint(x: 138.32, y: 137.02), controlPoint2: NSPoint(x: 145.13, y: 128.32))
        bezierPath.curve(to: NSPoint(x: 150.34, y: 86.61), controlPoint1: NSPoint(x: 152.64, y: 108.07), controlPoint2: NSPoint(x: 153.15, y: 97.04))
        bezierPath.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.9))
        strokeColor9.setStroke()
        bezierPath.lineWidth = 10
        bezierPath.miterLimit = 4
        bezierPath.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = NSBezierPath()
        bezier2Path.move(to: NSPoint(x: 50.49, y: 84.63))
        bezier2Path.curve(to: NSPoint(x: 50.69, y: 116.25), controlPoint1: NSPoint(x: 47.27, y: 94.93), controlPoint2: NSPoint(x: 47.34, y: 105.98))
        bezier2Path.curve(to: NSPoint(x: 69.17, y: 141.9), controlPoint1: NSPoint(x: 54.04, y: 126.51), controlPoint2: NSPoint(x: 60.5, y: 135.47))
        bezier2Path.curve(to: NSPoint(x: 99.1, y: 152.11), controlPoint1: NSPoint(x: 77.85, y: 148.33), controlPoint2: NSPoint(x: 88.3, y: 151.89))
        bezier2Path.curve(to: NSPoint(x: 129.4, y: 143.09), controlPoint1: NSPoint(x: 109.89, y: 152.32), controlPoint2: NSPoint(x: 120.48, y: 149.17))
        bezier2Path.curve(to: NSPoint(x: 148.88, y: 118.2), controlPoint1: NSPoint(x: 138.32, y: 137.02), controlPoint2: NSPoint(x: 145.13, y: 128.32))
        bezier2Path.curve(to: NSPoint(x: 150.34, y: 86.61), controlPoint1: NSPoint(x: 152.64, y: 108.07), controlPoint2: NSPoint(x: 153.15, y: 97.04))
        bezier2Path.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.9))
        strokeColor10.setStroke()
        bezier2Path.lineWidth = 10
        bezier2Path.miterLimit = 4
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = NSBezierPath()
        bezier3Path.move(to: NSPoint(x: 150.34, y: 86.61))
        bezier3Path.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.89))
        strokeColor11.setStroke()
        bezier3Path.lineWidth = 10
        bezier3Path.miterLimit = 4
        bezier3Path.stroke()


        //// Group 2
        //// Bezier 5 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.7)

        let bezier5Path = NSBezierPath()
        bezier5Path.move(to: NSPoint(x: 89.76, y: 67.61))
        bezier5Path.line(to: NSPoint(x: 91.4, y: 67.61))
        bezier5Path.line(to: NSPoint(x: 91.4, y: 62.95))
        bezier5Path.line(to: NSPoint(x: 93.48, y: 65.36))
        bezier5Path.line(to: NSPoint(x: 95.55, y: 65.36))
        bezier5Path.line(to: NSPoint(x: 93.32, y: 62.91))
        bezier5Path.line(to: NSPoint(x: 95.64, y: 59))
        bezier5Path.line(to: NSPoint(x: 93.62, y: 59))
        bezier5Path.line(to: NSPoint(x: 92.09, y: 61.73))
        bezier5Path.line(to: NSPoint(x: 91.4, y: 61.01))
        bezier5Path.line(to: NSPoint(x: 91.4, y: 59))
        bezier5Path.line(to: NSPoint(x: 89.76, y: 59))
        bezier5Path.line(to: NSPoint(x: 89.76, y: 67.61))
        bezier5Path.close()
        bezier5Path.move(to: NSPoint(x: 101.46, y: 64.89))
        bezier5Path.curve(to: NSPoint(x: 101.1, y: 65.85), controlPoint1: NSPoint(x: 101.46, y: 65.34), controlPoint2: NSPoint(x: 101.34, y: 65.66))
        bezier5Path.curve(to: NSPoint(x: 100.11, y: 66.14), controlPoint1: NSPoint(x: 100.87, y: 66.04), controlPoint2: NSPoint(x: 100.54, y: 66.14))
        bezier5Path.line(to: NSPoint(x: 98.43, y: 66.14))
        bezier5Path.line(to: NSPoint(x: 98.43, y: 63.59))
        bezier5Path.line(to: NSPoint(x: 100.11, y: 63.59))
        bezier5Path.curve(to: NSPoint(x: 101.1, y: 63.9), controlPoint1: NSPoint(x: 100.54, y: 63.59), controlPoint2: NSPoint(x: 100.87, y: 63.7))
        bezier5Path.curve(to: NSPoint(x: 101.46, y: 64.89), controlPoint1: NSPoint(x: 101.34, y: 64.11), controlPoint2: NSPoint(x: 101.46, y: 64.44))
        bezier5Path.close()
        bezier5Path.move(to: NSPoint(x: 103.24, y: 64.9))
        bezier5Path.curve(to: NSPoint(x: 102.47, y: 62.74), controlPoint1: NSPoint(x: 103.24, y: 63.88), controlPoint2: NSPoint(x: 102.99, y: 63.16))
        bezier5Path.curve(to: NSPoint(x: 100.26, y: 62.1), controlPoint1: NSPoint(x: 101.96, y: 62.32), controlPoint2: NSPoint(x: 101.22, y: 62.1))
        bezier5Path.line(to: NSPoint(x: 98.43, y: 62.1))
        bezier5Path.line(to: NSPoint(x: 98.43, y: 59))
        bezier5Path.line(to: NSPoint(x: 96.63, y: 59))
        bezier5Path.line(to: NSPoint(x: 96.63, y: 67.64))
        bezier5Path.line(to: NSPoint(x: 100.4, y: 67.64))
        bezier5Path.curve(to: NSPoint(x: 102.47, y: 66.97), controlPoint1: NSPoint(x: 101.26, y: 67.64), controlPoint2: NSPoint(x: 101.96, y: 67.41))
        bezier5Path.curve(to: NSPoint(x: 103.24, y: 64.9), controlPoint1: NSPoint(x: 102.99, y: 66.52), controlPoint2: NSPoint(x: 103.24, y: 65.83))
        bezier5Path.close()
        bezier5Path.move(to: NSPoint(x: 107.98, y: 62.1))
        bezier5Path.curve(to: NSPoint(x: 107.66, y: 61.94), controlPoint1: NSPoint(x: 107.88, y: 62.04), controlPoint2: NSPoint(x: 107.77, y: 61.98))
        bezier5Path.curve(to: NSPoint(x: 107.22, y: 61.83), controlPoint1: NSPoint(x: 107.56, y: 61.9), controlPoint2: NSPoint(x: 107.41, y: 61.86))
        bezier5Path.line(to: NSPoint(x: 106.85, y: 61.76))
        bezier5Path.curve(to: NSPoint(x: 106.09, y: 61.53), controlPoint1: NSPoint(x: 106.5, y: 61.7), controlPoint2: NSPoint(x: 106.24, y: 61.62))
        bezier5Path.curve(to: NSPoint(x: 105.71, y: 60.82), controlPoint1: NSPoint(x: 105.83, y: 61.38), controlPoint2: NSPoint(x: 105.71, y: 61.14))
        bezier5Path.curve(to: NSPoint(x: 105.94, y: 60.2), controlPoint1: NSPoint(x: 105.71, y: 60.54), controlPoint2: NSPoint(x: 105.78, y: 60.33))
        bezier5Path.curve(to: NSPoint(x: 106.52, y: 60.01), controlPoint1: NSPoint(x: 106.1, y: 60.08), controlPoint2: NSPoint(x: 106.29, y: 60.01))
        bezier5Path.curve(to: NSPoint(x: 107.51, y: 60.33), controlPoint1: NSPoint(x: 106.88, y: 60.01), controlPoint2: NSPoint(x: 107.21, y: 60.12))
        bezier5Path.curve(to: NSPoint(x: 107.98, y: 61.48), controlPoint1: NSPoint(x: 107.81, y: 60.54), controlPoint2: NSPoint(x: 107.97, y: 60.93))
        bezier5Path.line(to: NSPoint(x: 107.98, y: 62.1))
        bezier5Path.close()
        bezier5Path.move(to: NSPoint(x: 106.97, y: 62.88))
        bezier5Path.curve(to: NSPoint(x: 107.63, y: 63.03), controlPoint1: NSPoint(x: 107.28, y: 62.92), controlPoint2: NSPoint(x: 107.5, y: 62.97))
        bezier5Path.curve(to: NSPoint(x: 107.99, y: 63.51), controlPoint1: NSPoint(x: 107.87, y: 63.13), controlPoint2: NSPoint(x: 107.99, y: 63.29))
        bezier5Path.curve(to: NSPoint(x: 107.71, y: 64.04), controlPoint1: NSPoint(x: 107.99, y: 63.77), controlPoint2: NSPoint(x: 107.9, y: 63.95))
        bezier5Path.curve(to: NSPoint(x: 106.92, y: 64.2), controlPoint1: NSPoint(x: 107.54, y: 64.15), controlPoint2: NSPoint(x: 107.27, y: 64.2))
        bezier5Path.curve(to: NSPoint(x: 106.08, y: 63.9), controlPoint1: NSPoint(x: 106.52, y: 64.2), controlPoint2: NSPoint(x: 106.24, y: 64.1))
        bezier5Path.curve(to: NSPoint(x: 105.85, y: 63.32), controlPoint1: NSPoint(x: 105.96, y: 63.76), controlPoint2: NSPoint(x: 105.88, y: 63.56))
        bezier5Path.line(to: NSPoint(x: 104.23, y: 63.32))
        bezier5Path.curve(to: NSPoint(x: 104.7, y: 64.69), controlPoint1: NSPoint(x: 104.27, y: 63.88), controlPoint2: NSPoint(x: 104.43, y: 64.34))
        bezier5Path.curve(to: NSPoint(x: 106.98, y: 65.54), controlPoint1: NSPoint(x: 105.14, y: 65.26), controlPoint2: NSPoint(x: 105.9, y: 65.54))
        bezier5Path.curve(to: NSPoint(x: 108.84, y: 65.12), controlPoint1: NSPoint(x: 107.68, y: 65.54), controlPoint2: NSPoint(x: 108.3, y: 65.4))
        bezier5Path.curve(to: NSPoint(x: 109.65, y: 63.55), controlPoint1: NSPoint(x: 109.38, y: 64.85), controlPoint2: NSPoint(x: 109.65, y: 64.32))
        bezier5Path.line(to: NSPoint(x: 109.65, y: 60.62))
        bezier5Path.curve(to: NSPoint(x: 109.67, y: 59.88), controlPoint1: NSPoint(x: 109.65, y: 60.42), controlPoint2: NSPoint(x: 109.66, y: 60.17))
        bezier5Path.curve(to: NSPoint(x: 109.77, y: 59.44), controlPoint1: NSPoint(x: 109.68, y: 59.67), controlPoint2: NSPoint(x: 109.71, y: 59.52))
        bezier5Path.curve(to: NSPoint(x: 110.01, y: 59.25), controlPoint1: NSPoint(x: 109.82, y: 59.36), controlPoint2: NSPoint(x: 109.9, y: 59.3))
        bezier5Path.line(to: NSPoint(x: 110.01, y: 59))
        bezier5Path.line(to: NSPoint(x: 108.2, y: 59))
        bezier5Path.curve(to: NSPoint(x: 108.09, y: 59.36), controlPoint1: NSPoint(x: 108.14, y: 59.13), controlPoint2: NSPoint(x: 108.11, y: 59.25))
        bezier5Path.curve(to: NSPoint(x: 108.04, y: 59.75), controlPoint1: NSPoint(x: 108.07, y: 59.48), controlPoint2: NSPoint(x: 108.05, y: 59.6))
        bezier5Path.curve(to: NSPoint(x: 107.25, y: 59.11), controlPoint1: NSPoint(x: 107.81, y: 59.5), controlPoint2: NSPoint(x: 107.55, y: 59.29))
        bezier5Path.curve(to: NSPoint(x: 106.03, y: 58.8), controlPoint1: NSPoint(x: 106.89, y: 58.9), controlPoint2: NSPoint(x: 106.48, y: 58.8))
        bezier5Path.curve(to: NSPoint(x: 104.59, y: 59.29), controlPoint1: NSPoint(x: 105.45, y: 58.8), controlPoint2: NSPoint(x: 104.97, y: 58.96))
        bezier5Path.curve(to: NSPoint(x: 104.03, y: 60.7), controlPoint1: NSPoint(x: 104.22, y: 59.62), controlPoint2: NSPoint(x: 104.03, y: 60.09))
        bezier5Path.curve(to: NSPoint(x: 104.94, y: 62.4), controlPoint1: NSPoint(x: 104.03, y: 61.48), controlPoint2: NSPoint(x: 104.33, y: 62.05))
        bezier5Path.curve(to: NSPoint(x: 106.4, y: 62.81), controlPoint1: NSPoint(x: 105.27, y: 62.6), controlPoint2: NSPoint(x: 105.76, y: 62.73))
        bezier5Path.line(to: NSPoint(x: 106.97, y: 62.88))
        bezier5Path.close()
        fillColor5.setFill()
        bezier5Path.fill()

        NSGraphicsContext.restoreGraphicsState()




        //// Group 3
        //// Bezier 6 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)

        let bezier6Path = NSBezierPath()
        bezier6Path.move(to: NSPoint(x: 101.56, y: 118))
        bezier6Path.line(to: NSPoint(x: 95.31, y: 118))
        bezier6Path.curve(to: NSPoint(x: 95, y: 118.31), controlPoint1: NSPoint(x: 95.14, y: 118), controlPoint2: NSPoint(x: 95, y: 118.14))
        bezier6Path.curve(to: NSPoint(x: 96.56, y: 119.88), controlPoint1: NSPoint(x: 95, y: 119.17), controlPoint2: NSPoint(x: 95.7, y: 119.88))
        bezier6Path.line(to: NSPoint(x: 100.31, y: 119.88))
        bezier6Path.curve(to: NSPoint(x: 101.88, y: 118.31), controlPoint1: NSPoint(x: 101.17, y: 119.88), controlPoint2: NSPoint(x: 101.88, y: 119.17))
        bezier6Path.curve(to: NSPoint(x: 101.56, y: 118), controlPoint1: NSPoint(x: 101.88, y: 118.14), controlPoint2: NSPoint(x: 101.73, y: 118))
        bezier6Path.close()
        bezier6Path.move(to: NSPoint(x: 95.68, y: 118.62))
        bezier6Path.line(to: NSPoint(x: 101.2, y: 118.62))
        bezier6Path.curve(to: NSPoint(x: 100.31, y: 119.25), controlPoint1: NSPoint(x: 101.07, y: 118.99), controlPoint2: NSPoint(x: 100.72, y: 119.25))
        bezier6Path.line(to: NSPoint(x: 96.56, y: 119.25))
        bezier6Path.curve(to: NSPoint(x: 95.68, y: 118.62), controlPoint1: NSPoint(x: 96.16, y: 119.25), controlPoint2: NSPoint(x: 95.81, y: 118.99))
        bezier6Path.close()
        fillColor5.setFill()
        bezier6Path.fill()

        NSGraphicsContext.restoreGraphicsState()


        //// Bezier 7 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)

        let bezier7Path = NSBezierPath()
        bezier7Path.move(to: NSPoint(x: 99.69, y: 119.25))
        bezier7Path.curve(to: NSPoint(x: 99.38, y: 119.56), controlPoint1: NSPoint(x: 99.52, y: 119.25), controlPoint2: NSPoint(x: 99.38, y: 119.39))
        bezier7Path.line(to: NSPoint(x: 99.38, y: 128.62))
        bezier7Path.line(to: NSPoint(x: 97.5, y: 128.62))
        bezier7Path.line(to: NSPoint(x: 97.5, y: 119.56))
        bezier7Path.curve(to: NSPoint(x: 97.19, y: 119.25), controlPoint1: NSPoint(x: 97.5, y: 119.39), controlPoint2: NSPoint(x: 97.36, y: 119.25))
        bezier7Path.curve(to: NSPoint(x: 96.88, y: 119.56), controlPoint1: NSPoint(x: 97.02, y: 119.25), controlPoint2: NSPoint(x: 96.88, y: 119.39))
        bezier7Path.line(to: NSPoint(x: 96.88, y: 128.94))
        bezier7Path.curve(to: NSPoint(x: 97.19, y: 129.25), controlPoint1: NSPoint(x: 96.88, y: 129.11), controlPoint2: NSPoint(x: 97.02, y: 129.25))
        bezier7Path.line(to: NSPoint(x: 99.69, y: 129.25))
        bezier7Path.curve(to: NSPoint(x: 100, y: 128.94), controlPoint1: NSPoint(x: 99.86, y: 129.25), controlPoint2: NSPoint(x: 100, y: 129.11))
        bezier7Path.line(to: NSPoint(x: 100, y: 119.56))
        bezier7Path.curve(to: NSPoint(x: 99.69, y: 119.25), controlPoint1: NSPoint(x: 100, y: 119.39), controlPoint2: NSPoint(x: 99.86, y: 119.25))
        bezier7Path.close()
        fillColor5.setFill()
        bezier7Path.fill()

        NSGraphicsContext.restoreGraphicsState()


        //// Bezier 8 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)

        let bezier8Path = NSBezierPath()
        bezier8Path.move(to: NSPoint(x: 99.69, y: 128.62))
        bezier8Path.line(to: NSPoint(x: 97.19, y: 128.62))
        bezier8Path.curve(to: NSPoint(x: 96.88, y: 128.94), controlPoint1: NSPoint(x: 97.02, y: 128.62), controlPoint2: NSPoint(x: 96.88, y: 128.76))
        bezier8Path.line(to: NSPoint(x: 96.88, y: 130.19))
        bezier8Path.curve(to: NSPoint(x: 97.19, y: 130.5), controlPoint1: NSPoint(x: 96.88, y: 130.36), controlPoint2: NSPoint(x: 97.02, y: 130.5))
        bezier8Path.line(to: NSPoint(x: 99.69, y: 130.5))
        bezier8Path.curve(to: NSPoint(x: 100, y: 130.19), controlPoint1: NSPoint(x: 99.86, y: 130.5), controlPoint2: NSPoint(x: 100, y: 130.36))
        bezier8Path.line(to: NSPoint(x: 100, y: 128.94))
        bezier8Path.curve(to: NSPoint(x: 99.69, y: 128.62), controlPoint1: NSPoint(x: 100, y: 128.76), controlPoint2: NSPoint(x: 99.86, y: 128.62))
        bezier8Path.close()
        bezier8Path.move(to: NSPoint(x: 97.5, y: 129.25))
        bezier8Path.line(to: NSPoint(x: 99.38, y: 129.25))
        bezier8Path.line(to: NSPoint(x: 99.38, y: 129.88))
        bezier8Path.line(to: NSPoint(x: 97.5, y: 129.88))
        bezier8Path.line(to: NSPoint(x: 97.5, y: 129.25))
        bezier8Path.close()
        fillColor5.setFill()
        bezier8Path.fill()

        NSGraphicsContext.restoreGraphicsState()


        //// Bezier 9 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)

        let bezier9Path = NSBezierPath()
        bezier9Path.move(to: NSPoint(x: 98.44, y: 129.88))
        bezier9Path.curve(to: NSPoint(x: 98.12, y: 130.19), controlPoint1: NSPoint(x: 98.27, y: 129.88), controlPoint2: NSPoint(x: 98.12, y: 130.01))
        bezier9Path.line(to: NSPoint(x: 98.12, y: 131.44))
        bezier9Path.curve(to: NSPoint(x: 98.44, y: 131.75), controlPoint1: NSPoint(x: 98.12, y: 131.61), controlPoint2: NSPoint(x: 98.27, y: 131.75))
        bezier9Path.curve(to: NSPoint(x: 98.75, y: 131.44), controlPoint1: NSPoint(x: 98.61, y: 131.75), controlPoint2: NSPoint(x: 98.75, y: 131.61))
        bezier9Path.line(to: NSPoint(x: 98.75, y: 130.19))
        bezier9Path.curve(to: NSPoint(x: 98.44, y: 129.88), controlPoint1: NSPoint(x: 98.75, y: 130.01), controlPoint2: NSPoint(x: 98.61, y: 129.88))
        bezier9Path.close()
        fillColor5.setFill()
        bezier9Path.fill()

        NSGraphicsContext.restoreGraphicsState()


        //// Bezier 10 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)

        let bezier10Path = NSBezierPath()
        bezier10Path.move(to: NSPoint(x: 101.56, y: 131.12))
        bezier10Path.line(to: NSPoint(x: 95.31, y: 131.12))
        bezier10Path.curve(to: NSPoint(x: 95, y: 131.44), controlPoint1: NSPoint(x: 95.14, y: 131.12), controlPoint2: NSPoint(x: 95, y: 131.26))
        bezier10Path.line(to: NSPoint(x: 95, y: 132.69))
        bezier10Path.curve(to: NSPoint(x: 95.31, y: 133), controlPoint1: NSPoint(x: 95, y: 132.86), controlPoint2: NSPoint(x: 95.14, y: 133))
        bezier10Path.line(to: NSPoint(x: 101.56, y: 133))
        bezier10Path.curve(to: NSPoint(x: 101.88, y: 132.69), controlPoint1: NSPoint(x: 101.73, y: 133), controlPoint2: NSPoint(x: 101.88, y: 132.86))
        bezier10Path.line(to: NSPoint(x: 101.88, y: 131.44))
        bezier10Path.curve(to: NSPoint(x: 101.56, y: 131.12), controlPoint1: NSPoint(x: 101.88, y: 131.26), controlPoint2: NSPoint(x: 101.73, y: 131.12))
        bezier10Path.close()
        bezier10Path.move(to: NSPoint(x: 95.62, y: 131.75))
        bezier10Path.line(to: NSPoint(x: 101.25, y: 131.75))
        bezier10Path.line(to: NSPoint(x: 101.25, y: 132.38))
        bezier10Path.line(to: NSPoint(x: 95.62, y: 132.38))
        bezier10Path.line(to: NSPoint(x: 95.62, y: 131.75))
        bezier10Path.close()
        fillColor5.setFill()
        bezier10Path.fill()

        NSGraphicsContext.restoreGraphicsState()


        //// Bezier 11 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)

        let bezier11Path = NSBezierPath()
        bezier11Path.move(to: NSPoint(x: 100.94, y: 120.5))
        bezier11Path.line(to: NSPoint(x: 99.69, y: 120.5))
        bezier11Path.curve(to: NSPoint(x: 99.38, y: 120.81), controlPoint1: NSPoint(x: 99.52, y: 120.5), controlPoint2: NSPoint(x: 99.38, y: 120.64))
        bezier11Path.line(to: NSPoint(x: 99.38, y: 122.06))
        bezier11Path.curve(to: NSPoint(x: 99.69, y: 122.38), controlPoint1: NSPoint(x: 99.38, y: 122.23), controlPoint2: NSPoint(x: 99.52, y: 122.38))
        bezier11Path.line(to: NSPoint(x: 100.94, y: 122.38))
        bezier11Path.curve(to: NSPoint(x: 101.25, y: 122.06), controlPoint1: NSPoint(x: 101.11, y: 122.38), controlPoint2: NSPoint(x: 101.25, y: 122.23))
        bezier11Path.line(to: NSPoint(x: 101.25, y: 120.81))
        bezier11Path.curve(to: NSPoint(x: 100.94, y: 120.5), controlPoint1: NSPoint(x: 101.25, y: 120.64), controlPoint2: NSPoint(x: 101.11, y: 120.5))
        bezier11Path.close()
        bezier11Path.move(to: NSPoint(x: 100, y: 121.12))
        bezier11Path.line(to: NSPoint(x: 100.62, y: 121.12))
        bezier11Path.line(to: NSPoint(x: 100.62, y: 121.75))
        bezier11Path.line(to: NSPoint(x: 100, y: 121.75))
        bezier11Path.line(to: NSPoint(x: 100, y: 121.12))
        bezier11Path.close()
        fillColor5.setFill()
        bezier11Path.fill()

        NSGraphicsContext.restoreGraphicsState()


        //// Bezier 12 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)

        let bezier12Path = NSBezierPath()
        bezier12Path.move(to: NSPoint(x: 101.56, y: 121.12))
        bezier12Path.line(to: NSPoint(x: 100.94, y: 121.12))
        bezier12Path.curve(to: NSPoint(x: 100.62, y: 121.44), controlPoint1: NSPoint(x: 100.77, y: 121.12), controlPoint2: NSPoint(x: 100.62, y: 121.27))
        bezier12Path.curve(to: NSPoint(x: 100.94, y: 121.75), controlPoint1: NSPoint(x: 100.62, y: 121.61), controlPoint2: NSPoint(x: 100.77, y: 121.75))
        bezier12Path.line(to: NSPoint(x: 101.56, y: 121.75))
        bezier12Path.curve(to: NSPoint(x: 103.12, y: 123.31), controlPoint1: NSPoint(x: 102.42, y: 121.75), controlPoint2: NSPoint(x: 103.12, y: 122.45))
        bezier12Path.line(to: NSPoint(x: 103.12, y: 128.94))
        bezier12Path.curve(to: NSPoint(x: 103.44, y: 129.25), controlPoint1: NSPoint(x: 103.12, y: 129.11), controlPoint2: NSPoint(x: 103.27, y: 129.25))
        bezier12Path.curve(to: NSPoint(x: 103.75, y: 128.94), controlPoint1: NSPoint(x: 103.61, y: 129.25), controlPoint2: NSPoint(x: 103.75, y: 129.11))
        bezier12Path.line(to: NSPoint(x: 103.75, y: 123.31))
        bezier12Path.curve(to: NSPoint(x: 101.56, y: 121.12), controlPoint1: NSPoint(x: 103.75, y: 122.11), controlPoint2: NSPoint(x: 102.77, y: 121.12))
        bezier12Path.close()
        fillColor5.setFill()
        bezier12Path.fill()

        NSGraphicsContext.restoreGraphicsState()


        //// Bezier 13 Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)

        let bezier13Path = NSBezierPath()
        bezier13Path.move(to: NSPoint(x: 104.06, y: 128.62))
        bezier13Path.line(to: NSPoint(x: 102.81, y: 128.62))
        bezier13Path.curve(to: NSPoint(x: 102.5, y: 128.94), controlPoint1: NSPoint(x: 102.64, y: 128.62), controlPoint2: NSPoint(x: 102.5, y: 128.76))
        bezier13Path.line(to: NSPoint(x: 102.5, y: 130.81))
        bezier13Path.curve(to: NSPoint(x: 102.81, y: 131.12), controlPoint1: NSPoint(x: 102.5, y: 130.99), controlPoint2: NSPoint(x: 102.64, y: 131.12))
        bezier13Path.line(to: NSPoint(x: 104.06, y: 131.12))
        bezier13Path.curve(to: NSPoint(x: 104.38, y: 130.81), controlPoint1: NSPoint(x: 104.23, y: 131.12), controlPoint2: NSPoint(x: 104.38, y: 130.99))
        bezier13Path.line(to: NSPoint(x: 104.38, y: 128.94))
        bezier13Path.curve(to: NSPoint(x: 104.06, y: 128.62), controlPoint1: NSPoint(x: 104.38, y: 128.76), controlPoint2: NSPoint(x: 104.23, y: 128.62))
        bezier13Path.close()
        bezier13Path.move(to: NSPoint(x: 103.12, y: 129.25))
        bezier13Path.line(to: NSPoint(x: 103.75, y: 129.25))
        bezier13Path.line(to: NSPoint(x: 103.75, y: 130.5))
        bezier13Path.line(to: NSPoint(x: 103.12, y: 130.5))
        bezier13Path.line(to: NSPoint(x: 103.12, y: 129.25))
        bezier13Path.close()
        fillColor5.setFill()
        bezier13Path.fill()

        NSGraphicsContext.restoreGraphicsState()




        //// Pointer
        NSGraphicsContext.saveGraphicsState()
        context.translateBy(x: 99.5, y: 100.5)
        context.rotate(by: pressureValue * CGFloat.pi/180)

        context.setShadow(offset: NSSize(width: shadow.shadowOffset.width * resizedShadowScale, height: shadow.shadowOffset.height * resizedShadowScale), blur: shadow.shadowBlurRadius * resizedShadowScale, color: shadow.shadowColor!.cgColor)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier 4 Drawing
        let bezier4Path = NSBezierPath()
        bezier4Path.move(to: NSPoint(x: 0.5, y: -0.5))
        bezier4Path.line(to: NSPoint(x: -32.5, y: -37.5))
        strokeColor5.setStroke()
        bezier4Path.lineWidth = 8
        bezier4Path.miterLimit = 4
        bezier4Path.lineCapStyle = .round
        bezier4Path.stroke()


        //// Oval 2 Drawing
        let oval2Path = NSBezierPath(ovalIn: NSRect(x: -7.5, y: -7.5, width: 15, height: 15))
        fillColor3.setFill()
        oval2Path.fill()


        context.endTransparencyLayer()

        NSGraphicsContext.restoreGraphicsState()
        
        NSGraphicsContext.restoreGraphicsState()

    }

    @objc dynamic public class func drawVolume(frame targetFrame: NSRect = NSRect(x: 0, y: 0, width: 200, height: 200), resizing: ResizingBehavior = .aspectFit, volumeValue: CGFloat = 0) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext
        
        //// Resize to Target Frame
        NSGraphicsContext.saveGraphicsState()
        let resizedFrame: NSRect = resizing.apply(rect: NSRect(x: 0, y: 0, width: 200, height: 200), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 200, y: resizedFrame.height / 200)
        let resizedShadowScale: CGFloat = min(resizedFrame.width / 200, resizedFrame.height / 200)


        //// Color Declarations
        let strokeColor5 = NSColor(red: 1, green: 1, blue: 1, alpha: 1)
        let fillColor3 = NSColor(red: 0.969, green: 0.969, blue: 0.969, alpha: 1)
        let strokeColor8 = NSColor(red: 0.286, green: 0.318, blue: 0.349, alpha: 1)
        let fillColor4 = NSColor(red: 0.886, green: 0.886, blue: 0.886, alpha: 1)
        let strokeColor9 = NSColor(red: 0.984, green: 0.733, blue: 0.082, alpha: 0.5)
        let strokeColor10 = NSColor(red: 0.173, green: 0.761, blue: 0.408, alpha: 0.5)
        let strokeColor11 = NSColor(red: 0.984, green: 0.082, blue: 0.082, alpha: 0.6)
        let fillColor5 = NSColor(red: 0.2, green: 0.2, blue: 0.2, alpha: 1)

        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = NSColor.black.withAlphaComponent(0.1)
        shadow.shadowOffset = NSSize(width: 3, height: -3)
        shadow.shadowBlurRadius = 5

        //// Volume Gauge
        //// Oval Drawing
        let ovalPath = NSBezierPath(ovalIn: NSRect(x: 30, y: 30, width: 140, height: 140))
        fillColor4.setFill()
        ovalPath.fill()
        strokeColor8.setStroke()
        ovalPath.lineWidth = 10
        ovalPath.stroke()


        //// Bezier Drawing
        let bezierPath = NSBezierPath()
        bezierPath.move(to: NSPoint(x: 68.63, y: 58.74))
        bezierPath.curve(to: NSPoint(x: 50.49, y: 84.63), controlPoint1: NSPoint(x: 60.04, y: 65.28), controlPoint2: NSPoint(x: 53.7, y: 74.33))
        bezierPath.curve(to: NSPoint(x: 50.69, y: 116.25), controlPoint1: NSPoint(x: 47.27, y: 94.93), controlPoint2: NSPoint(x: 47.34, y: 105.98))
        bezierPath.curve(to: NSPoint(x: 69.17, y: 141.9), controlPoint1: NSPoint(x: 54.04, y: 126.51), controlPoint2: NSPoint(x: 60.5, y: 135.47))
        bezierPath.curve(to: NSPoint(x: 99.1, y: 152.11), controlPoint1: NSPoint(x: 77.85, y: 148.33), controlPoint2: NSPoint(x: 88.3, y: 151.89))
        bezierPath.curve(to: NSPoint(x: 129.4, y: 143.09), controlPoint1: NSPoint(x: 109.89, y: 152.32), controlPoint2: NSPoint(x: 120.48, y: 149.17))
        bezierPath.curve(to: NSPoint(x: 148.89, y: 118.2), controlPoint1: NSPoint(x: 138.32, y: 137.02), controlPoint2: NSPoint(x: 145.13, y: 128.32))
        bezierPath.curve(to: NSPoint(x: 150.34, y: 86.61), controlPoint1: NSPoint(x: 152.64, y: 108.07), controlPoint2: NSPoint(x: 153.15, y: 97.04))
        bezierPath.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.9))
        strokeColor9.setStroke()
        bezierPath.lineWidth = 10
        bezierPath.miterLimit = 4
        bezierPath.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = NSBezierPath()
        bezier2Path.move(to: NSPoint(x: 50.49, y: 84.63))
        bezier2Path.curve(to: NSPoint(x: 50.69, y: 116.25), controlPoint1: NSPoint(x: 47.27, y: 94.93), controlPoint2: NSPoint(x: 47.34, y: 105.98))
        bezier2Path.curve(to: NSPoint(x: 69.17, y: 141.9), controlPoint1: NSPoint(x: 54.04, y: 126.51), controlPoint2: NSPoint(x: 60.5, y: 135.47))
        bezier2Path.curve(to: NSPoint(x: 99.1, y: 152.11), controlPoint1: NSPoint(x: 77.85, y: 148.33), controlPoint2: NSPoint(x: 88.3, y: 151.89))
        bezier2Path.curve(to: NSPoint(x: 129.4, y: 143.09), controlPoint1: NSPoint(x: 109.89, y: 152.32), controlPoint2: NSPoint(x: 120.48, y: 149.17))
        bezier2Path.curve(to: NSPoint(x: 148.88, y: 118.2), controlPoint1: NSPoint(x: 138.32, y: 137.02), controlPoint2: NSPoint(x: 145.13, y: 128.32))
        bezier2Path.curve(to: NSPoint(x: 150.34, y: 86.61), controlPoint1: NSPoint(x: 152.64, y: 108.07), controlPoint2: NSPoint(x: 153.15, y: 97.04))
        bezier2Path.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.9))
        strokeColor10.setStroke()
        bezier2Path.lineWidth = 10
        bezier2Path.miterLimit = 4
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = NSBezierPath()
        bezier3Path.move(to: NSPoint(x: 150.34, y: 86.61))
        bezier3Path.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.89))
        strokeColor11.setStroke()
        bezier3Path.lineWidth = 10
        bezier3Path.miterLimit = 4
        bezier3Path.stroke()


        //// Group 2
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.7)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier 5 Drawing
        let bezier5Path = NSBezierPath()
        bezier5Path.move(to: NSPoint(x: 102.92, y: 65.53))
        bezier5Path.curve(to: NSPoint(x: 103.75, y: 65.36), controlPoint1: NSPoint(x: 103.2, y: 65.53), controlPoint2: NSPoint(x: 103.47, y: 65.47))
        bezier5Path.curve(to: NSPoint(x: 104.49, y: 64.79), controlPoint1: NSPoint(x: 104.02, y: 65.25), controlPoint2: NSPoint(x: 104.27, y: 65.06))
        bezier5Path.curve(to: NSPoint(x: 104.86, y: 63.97), controlPoint1: NSPoint(x: 104.67, y: 64.57), controlPoint2: NSPoint(x: 104.79, y: 64.29))
        bezier5Path.curve(to: NSPoint(x: 104.91, y: 63.02), controlPoint1: NSPoint(x: 104.89, y: 63.75), controlPoint2: NSPoint(x: 104.91, y: 63.44))
        bezier5Path.line(to: NSPoint(x: 104.9, y: 59))
        bezier5Path.line(to: NSPoint(x: 103.19, y: 59))
        bezier5Path.line(to: NSPoint(x: 103.19, y: 63.07))
        bezier5Path.curve(to: NSPoint(x: 103.07, y: 63.66), controlPoint1: NSPoint(x: 103.19, y: 63.31), controlPoint2: NSPoint(x: 103.15, y: 63.51))
        bezier5Path.curve(to: NSPoint(x: 102.25, y: 64.11), controlPoint1: NSPoint(x: 102.93, y: 63.96), controlPoint2: NSPoint(x: 102.65, y: 64.11))
        bezier5Path.curve(to: NSPoint(x: 101.3, y: 63.53), controlPoint1: NSPoint(x: 101.79, y: 64.11), controlPoint2: NSPoint(x: 101.47, y: 63.92))
        bezier5Path.curve(to: NSPoint(x: 101.16, y: 62.8), controlPoint1: NSPoint(x: 101.21, y: 63.33), controlPoint2: NSPoint(x: 101.16, y: 63.09))
        bezier5Path.line(to: NSPoint(x: 101.16, y: 59))
        bezier5Path.line(to: NSPoint(x: 99.48, y: 59))
        bezier5Path.line(to: NSPoint(x: 99.48, y: 62.8))
        bezier5Path.curve(to: NSPoint(x: 99.37, y: 63.63), controlPoint1: NSPoint(x: 99.48, y: 63.18), controlPoint2: NSPoint(x: 99.44, y: 63.46))
        bezier5Path.curve(to: NSPoint(x: 98.54, y: 64.09), controlPoint1: NSPoint(x: 99.22, y: 63.94), controlPoint2: NSPoint(x: 98.95, y: 64.09))
        bezier5Path.curve(to: NSPoint(x: 97.58, y: 63.63), controlPoint1: NSPoint(x: 98.06, y: 64.09), controlPoint2: NSPoint(x: 97.74, y: 63.94))
        bezier5Path.curve(to: NSPoint(x: 97.44, y: 62.84), controlPoint1: NSPoint(x: 97.49, y: 63.45), controlPoint2: NSPoint(x: 97.44, y: 63.19))
        bezier5Path.line(to: NSPoint(x: 97.44, y: 59))
        bezier5Path.line(to: NSPoint(x: 95.75, y: 59))
        bezier5Path.line(to: NSPoint(x: 95.75, y: 65.37))
        bezier5Path.line(to: NSPoint(x: 97.37, y: 65.37))
        bezier5Path.line(to: NSPoint(x: 97.37, y: 64.44))
        bezier5Path.curve(to: NSPoint(x: 97.96, y: 65.15), controlPoint1: NSPoint(x: 97.58, y: 64.77), controlPoint2: NSPoint(x: 97.78, y: 65.01))
        bezier5Path.curve(to: NSPoint(x: 99.22, y: 65.53), controlPoint1: NSPoint(x: 98.28, y: 65.4), controlPoint2: NSPoint(x: 98.7, y: 65.53))
        bezier5Path.curve(to: NSPoint(x: 100.4, y: 65.2), controlPoint1: NSPoint(x: 99.71, y: 65.53), controlPoint2: NSPoint(x: 100.1, y: 65.42))
        bezier5Path.curve(to: NSPoint(x: 100.95, y: 64.44), controlPoint1: NSPoint(x: 100.64, y: 65.01), controlPoint2: NSPoint(x: 100.83, y: 64.75))
        bezier5Path.curve(to: NSPoint(x: 101.77, y: 65.26), controlPoint1: NSPoint(x: 101.17, y: 64.81), controlPoint2: NSPoint(x: 101.44, y: 65.09))
        bezier5Path.curve(to: NSPoint(x: 102.92, y: 65.53), controlPoint1: NSPoint(x: 102.11, y: 65.44), controlPoint2: NSPoint(x: 102.49, y: 65.53))
        bezier5Path.close()
        fillColor5.setFill()
        bezier5Path.fill()


        context.endTransparencyLayer()
        NSGraphicsContext.restoreGraphicsState()


        //// Group 3
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.7)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier 6 Drawing
        let bezier6Path = NSBezierPath()
        bezier6Path.move(to: NSPoint(x: 106.3, y: 66.74))
        bezier6Path.curve(to: NSPoint(x: 106.41, y: 66.18), controlPoint1: NSPoint(x: 106.3, y: 66.51), controlPoint2: NSPoint(x: 106.34, y: 66.32))
        bezier6Path.curve(to: NSPoint(x: 107.15, y: 65.77), controlPoint1: NSPoint(x: 106.55, y: 65.9), controlPoint2: NSPoint(x: 106.8, y: 65.77))
        bezier6Path.curve(to: NSPoint(x: 107.72, y: 65.99), controlPoint1: NSPoint(x: 107.37, y: 65.77), controlPoint2: NSPoint(x: 107.56, y: 65.84))
        bezier6Path.curve(to: NSPoint(x: 107.97, y: 66.64), controlPoint1: NSPoint(x: 107.89, y: 66.14), controlPoint2: NSPoint(x: 107.97, y: 66.36))
        bezier6Path.curve(to: NSPoint(x: 107.52, y: 67.38), controlPoint1: NSPoint(x: 107.97, y: 67.01), controlPoint2: NSPoint(x: 107.82, y: 67.26))
        bezier6Path.curve(to: NSPoint(x: 106.7, y: 67.49), controlPoint1: NSPoint(x: 107.34, y: 67.45), controlPoint2: NSPoint(x: 107.07, y: 67.49))
        bezier6Path.line(to: NSPoint(x: 106.7, y: 68.29))
        bezier6Path.curve(to: NSPoint(x: 107.46, y: 68.39), controlPoint1: NSPoint(x: 107.07, y: 68.29), controlPoint2: NSPoint(x: 107.32, y: 68.33))
        bezier6Path.curve(to: NSPoint(x: 107.83, y: 69.06), controlPoint1: NSPoint(x: 107.71, y: 68.5), controlPoint2: NSPoint(x: 107.83, y: 68.72))
        bezier6Path.curve(to: NSPoint(x: 107.64, y: 69.58), controlPoint1: NSPoint(x: 107.83, y: 69.27), controlPoint2: NSPoint(x: 107.77, y: 69.45))
        bezier6Path.curve(to: NSPoint(x: 107.11, y: 69.79), controlPoint1: NSPoint(x: 107.52, y: 69.72), controlPoint2: NSPoint(x: 107.34, y: 69.79))
        bezier6Path.curve(to: NSPoint(x: 106.53, y: 69.54), controlPoint1: NSPoint(x: 106.85, y: 69.79), controlPoint2: NSPoint(x: 106.65, y: 69.7))
        bezier6Path.curve(to: NSPoint(x: 106.35, y: 68.87), controlPoint1: NSPoint(x: 106.4, y: 69.37), controlPoint2: NSPoint(x: 106.35, y: 69.15))
        bezier6Path.line(to: NSPoint(x: 105.31, y: 68.87))
        bezier6Path.curve(to: NSPoint(x: 105.46, y: 69.67), controlPoint1: NSPoint(x: 105.32, y: 69.15), controlPoint2: NSPoint(x: 105.37, y: 69.42))
        bezier6Path.curve(to: NSPoint(x: 105.89, y: 70.28), controlPoint1: NSPoint(x: 105.55, y: 69.89), controlPoint2: NSPoint(x: 105.69, y: 70.09))
        bezier6Path.curve(to: NSPoint(x: 106.41, y: 70.59), controlPoint1: NSPoint(x: 106.03, y: 70.41), controlPoint2: NSPoint(x: 106.21, y: 70.52))
        bezier6Path.curve(to: NSPoint(x: 107.14, y: 70.69), controlPoint1: NSPoint(x: 106.61, y: 70.66), controlPoint2: NSPoint(x: 106.85, y: 70.69))
        bezier6Path.curve(to: NSPoint(x: 108.45, y: 70.27), controlPoint1: NSPoint(x: 107.69, y: 70.69), controlPoint2: NSPoint(x: 108.12, y: 70.55))
        bezier6Path.curve(to: NSPoint(x: 108.95, y: 69.15), controlPoint1: NSPoint(x: 108.79, y: 69.99), controlPoint2: NSPoint(x: 108.95, y: 69.62))
        bezier6Path.curve(to: NSPoint(x: 108.66, y: 68.3), controlPoint1: NSPoint(x: 108.95, y: 68.81), controlPoint2: NSPoint(x: 108.85, y: 68.53))
        bezier6Path.curve(to: NSPoint(x: 108.27, y: 68.01), controlPoint1: NSPoint(x: 108.53, y: 68.16), controlPoint2: NSPoint(x: 108.4, y: 68.06))
        bezier6Path.curve(to: NSPoint(x: 108.7, y: 67.75), controlPoint1: NSPoint(x: 108.37, y: 68.01), controlPoint2: NSPoint(x: 108.51, y: 67.92))
        bezier6Path.curve(to: NSPoint(x: 109.13, y: 66.67), controlPoint1: NSPoint(x: 108.99, y: 67.48), controlPoint2: NSPoint(x: 109.13, y: 67.12))
        bezier6Path.curve(to: NSPoint(x: 108.63, y: 65.4), controlPoint1: NSPoint(x: 109.13, y: 66.19), controlPoint2: NSPoint(x: 108.96, y: 65.77))
        bezier6Path.curve(to: NSPoint(x: 107.16, y: 64.86), controlPoint1: NSPoint(x: 108.3, y: 65.04), controlPoint2: NSPoint(x: 107.81, y: 64.86))
        bezier6Path.curve(to: NSPoint(x: 105.48, y: 65.65), controlPoint1: NSPoint(x: 106.35, y: 64.86), controlPoint2: NSPoint(x: 105.8, y: 65.12))
        bezier6Path.curve(to: NSPoint(x: 105.21, y: 66.74), controlPoint1: NSPoint(x: 105.32, y: 65.92), controlPoint2: NSPoint(x: 105.23, y: 66.29))
        bezier6Path.line(to: NSPoint(x: 106.3, y: 66.74))
        bezier6Path.close()
        fillColor5.setFill()
        bezier6Path.fill()


        context.endTransparencyLayer()
        NSGraphicsContext.restoreGraphicsState()


        //// Group 4
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier 7 Drawing
        let bezier7Path = NSBezierPath()
        bezier7Path.move(to: NSPoint(x: 93.31, y: 128.88))
        bezier7Path.curve(to: NSPoint(x: 93.62, y: 129.19), controlPoint1: NSPoint(x: 93.48, y: 128.88), controlPoint2: NSPoint(x: 93.62, y: 129.01))
        bezier7Path.line(to: NSPoint(x: 93.62, y: 130.93))
        bezier7Path.line(to: NSPoint(x: 96.22, y: 128.34))
        bezier7Path.curve(to: NSPoint(x: 96.44, y: 128.25), controlPoint1: NSPoint(x: 96.28, y: 128.28), controlPoint2: NSPoint(x: 96.36, y: 128.25))
        bezier7Path.curve(to: NSPoint(x: 96.66, y: 128.34), controlPoint1: NSPoint(x: 96.52, y: 128.25), controlPoint2: NSPoint(x: 96.6, y: 128.28))
        bezier7Path.curve(to: NSPoint(x: 96.66, y: 128.78), controlPoint1: NSPoint(x: 96.78, y: 128.46), controlPoint2: NSPoint(x: 96.78, y: 128.66))
        bezier7Path.line(to: NSPoint(x: 94.07, y: 131.38))
        bezier7Path.line(to: NSPoint(x: 95.81, y: 131.38))
        bezier7Path.curve(to: NSPoint(x: 96.12, y: 131.69), controlPoint1: NSPoint(x: 95.98, y: 131.38), controlPoint2: NSPoint(x: 96.12, y: 131.51))
        bezier7Path.curve(to: NSPoint(x: 95.81, y: 132), controlPoint1: NSPoint(x: 96.12, y: 131.86), controlPoint2: NSPoint(x: 95.98, y: 132))
        bezier7Path.line(to: NSPoint(x: 93.31, y: 132))
        bezier7Path.curve(to: NSPoint(x: 93.26, y: 131.99), controlPoint1: NSPoint(x: 93.29, y: 132), controlPoint2: NSPoint(x: 93.28, y: 131.99))
        bezier7Path.curve(to: NSPoint(x: 93.19, y: 131.98), controlPoint1: NSPoint(x: 93.24, y: 131.99), controlPoint2: NSPoint(x: 93.22, y: 131.99))
        bezier7Path.curve(to: NSPoint(x: 93.09, y: 131.91), controlPoint1: NSPoint(x: 93.16, y: 131.96), controlPoint2: NSPoint(x: 93.12, y: 131.94))
        bezier7Path.curve(to: NSPoint(x: 93.08, y: 131.9), controlPoint1: NSPoint(x: 93.09, y: 131.91), controlPoint2: NSPoint(x: 93.09, y: 131.9))
        bezier7Path.curve(to: NSPoint(x: 93.02, y: 131.81), controlPoint1: NSPoint(x: 93.06, y: 131.87), controlPoint2: NSPoint(x: 93.04, y: 131.84))
        bezier7Path.curve(to: NSPoint(x: 93, y: 131.69), controlPoint1: NSPoint(x: 93.01, y: 131.77), controlPoint2: NSPoint(x: 93, y: 131.73))
        bezier7Path.line(to: NSPoint(x: 93, y: 129.19))
        bezier7Path.curve(to: NSPoint(x: 93.31, y: 128.88), controlPoint1: NSPoint(x: 93, y: 129.01), controlPoint2: NSPoint(x: 93.14, y: 128.88))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 95.81, y: 117.62))
        bezier7Path.line(to: NSPoint(x: 94.07, y: 117.62))
        bezier7Path.line(to: NSPoint(x: 96.03, y: 119.59))
        bezier7Path.curve(to: NSPoint(x: 96.03, y: 120.03), controlPoint1: NSPoint(x: 96.16, y: 119.71), controlPoint2: NSPoint(x: 96.16, y: 119.91))
        bezier7Path.curve(to: NSPoint(x: 95.59, y: 120.03), controlPoint1: NSPoint(x: 95.91, y: 120.16), controlPoint2: NSPoint(x: 95.71, y: 120.16))
        bezier7Path.line(to: NSPoint(x: 93.62, y: 118.07))
        bezier7Path.line(to: NSPoint(x: 93.62, y: 119.81))
        bezier7Path.curve(to: NSPoint(x: 93.31, y: 120.12), controlPoint1: NSPoint(x: 93.62, y: 119.98), controlPoint2: NSPoint(x: 93.48, y: 120.12))
        bezier7Path.curve(to: NSPoint(x: 93, y: 119.81), controlPoint1: NSPoint(x: 93.14, y: 120.12), controlPoint2: NSPoint(x: 93, y: 119.98))
        bezier7Path.line(to: NSPoint(x: 93, y: 117.31))
        bezier7Path.curve(to: NSPoint(x: 93.02, y: 117.19), controlPoint1: NSPoint(x: 93, y: 117.27), controlPoint2: NSPoint(x: 93.01, y: 117.23))
        bezier7Path.curve(to: NSPoint(x: 93.06, y: 117.14), controlPoint1: NSPoint(x: 93.03, y: 117.17), controlPoint2: NSPoint(x: 93.05, y: 117.16))
        bezier7Path.curve(to: NSPoint(x: 93.09, y: 117.09), controlPoint1: NSPoint(x: 93.07, y: 117.12), controlPoint2: NSPoint(x: 93.08, y: 117.11))
        bezier7Path.curve(to: NSPoint(x: 93.13, y: 117.07), controlPoint1: NSPoint(x: 93.1, y: 117.08), controlPoint2: NSPoint(x: 93.11, y: 117.08))
        bezier7Path.curve(to: NSPoint(x: 93.19, y: 117.03), controlPoint1: NSPoint(x: 93.15, y: 117.05), controlPoint2: NSPoint(x: 93.17, y: 117.03))
        bezier7Path.curve(to: NSPoint(x: 93.31, y: 117), controlPoint1: NSPoint(x: 93.23, y: 117.01), controlPoint2: NSPoint(x: 93.27, y: 117))
        bezier7Path.line(to: NSPoint(x: 95.81, y: 117))
        bezier7Path.curve(to: NSPoint(x: 96.12, y: 117.31), controlPoint1: NSPoint(x: 95.98, y: 117), controlPoint2: NSPoint(x: 96.12, y: 117.14))
        bezier7Path.curve(to: NSPoint(x: 95.81, y: 117.62), controlPoint1: NSPoint(x: 96.12, y: 117.48), controlPoint2: NSPoint(x: 95.98, y: 117.62))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 107.99, y: 131.75))
        bezier7Path.curve(to: NSPoint(x: 107.98, y: 131.81), controlPoint1: NSPoint(x: 107.98, y: 131.77), controlPoint2: NSPoint(x: 107.98, y: 131.79))
        bezier7Path.curve(to: NSPoint(x: 107.81, y: 131.98), controlPoint1: NSPoint(x: 107.94, y: 131.88), controlPoint2: NSPoint(x: 107.88, y: 131.94))
        bezier7Path.curve(to: NSPoint(x: 107.75, y: 131.99), controlPoint1: NSPoint(x: 107.79, y: 131.98), controlPoint2: NSPoint(x: 107.77, y: 131.98))
        bezier7Path.curve(to: NSPoint(x: 107.69, y: 132), controlPoint1: NSPoint(x: 107.73, y: 131.99), controlPoint2: NSPoint(x: 107.71, y: 132))
        bezier7Path.line(to: NSPoint(x: 105.19, y: 132))
        bezier7Path.curve(to: NSPoint(x: 104.88, y: 131.69), controlPoint1: NSPoint(x: 105.02, y: 132), controlPoint2: NSPoint(x: 104.88, y: 131.86))
        bezier7Path.curve(to: NSPoint(x: 105.19, y: 131.38), controlPoint1: NSPoint(x: 104.88, y: 131.51), controlPoint2: NSPoint(x: 105.02, y: 131.38))
        bezier7Path.line(to: NSPoint(x: 106.93, y: 131.38))
        bezier7Path.line(to: NSPoint(x: 104.34, y: 128.78))
        bezier7Path.curve(to: NSPoint(x: 104.34, y: 128.34), controlPoint1: NSPoint(x: 104.22, y: 128.66), controlPoint2: NSPoint(x: 104.22, y: 128.46))
        bezier7Path.curve(to: NSPoint(x: 104.56, y: 128.25), controlPoint1: NSPoint(x: 104.4, y: 128.28), controlPoint2: NSPoint(x: 104.48, y: 128.25))
        bezier7Path.curve(to: NSPoint(x: 104.78, y: 128.34), controlPoint1: NSPoint(x: 104.64, y: 128.25), controlPoint2: NSPoint(x: 104.72, y: 128.28))
        bezier7Path.line(to: NSPoint(x: 107.38, y: 130.93))
        bezier7Path.line(to: NSPoint(x: 107.38, y: 129.19))
        bezier7Path.curve(to: NSPoint(x: 107.69, y: 128.88), controlPoint1: NSPoint(x: 107.38, y: 129.01), controlPoint2: NSPoint(x: 107.52, y: 128.88))
        bezier7Path.curve(to: NSPoint(x: 108, y: 129.19), controlPoint1: NSPoint(x: 107.86, y: 128.88), controlPoint2: NSPoint(x: 108, y: 129.01))
        bezier7Path.line(to: NSPoint(x: 108, y: 131.69))
        bezier7Path.curve(to: NSPoint(x: 107.99, y: 131.75), controlPoint1: NSPoint(x: 108, y: 131.71), controlPoint2: NSPoint(x: 107.99, y: 131.73))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 104.88, y: 126.69))
        bezier7Path.curve(to: NSPoint(x: 104.87, y: 126.73), controlPoint1: NSPoint(x: 104.88, y: 126.7), controlPoint2: NSPoint(x: 104.87, y: 126.72))
        bezier7Path.curve(to: NSPoint(x: 104.86, y: 126.78), controlPoint1: NSPoint(x: 104.86, y: 126.75), controlPoint2: NSPoint(x: 104.86, y: 126.76))
        bezier7Path.curve(to: NSPoint(x: 104.83, y: 126.85), controlPoint1: NSPoint(x: 104.85, y: 126.81), controlPoint2: NSPoint(x: 104.84, y: 126.83))
        bezier7Path.curve(to: NSPoint(x: 104.81, y: 126.88), controlPoint1: NSPoint(x: 104.82, y: 126.85), controlPoint2: NSPoint(x: 104.82, y: 126.87))
        bezier7Path.line(to: NSPoint(x: 102.94, y: 129.38))
        bezier7Path.curve(to: NSPoint(x: 102.69, y: 129.5), controlPoint1: NSPoint(x: 102.88, y: 129.45), controlPoint2: NSPoint(x: 102.78, y: 129.5))
        bezier7Path.line(to: NSPoint(x: 98.31, y: 129.5))
        bezier7Path.curve(to: NSPoint(x: 98.06, y: 129.38), controlPoint1: NSPoint(x: 98.21, y: 129.5), controlPoint2: NSPoint(x: 98.12, y: 129.45))
        bezier7Path.line(to: NSPoint(x: 96.19, y: 126.88))
        bezier7Path.curve(to: NSPoint(x: 96.17, y: 126.84), controlPoint1: NSPoint(x: 96.18, y: 126.86), controlPoint2: NSPoint(x: 96.18, y: 126.85))
        bezier7Path.curve(to: NSPoint(x: 96.14, y: 126.79), controlPoint1: NSPoint(x: 96.16, y: 126.82), controlPoint2: NSPoint(x: 96.15, y: 126.81))
        bezier7Path.curve(to: NSPoint(x: 96.13, y: 126.72), controlPoint1: NSPoint(x: 96.14, y: 126.77), controlPoint2: NSPoint(x: 96.13, y: 126.74))
        bezier7Path.curve(to: NSPoint(x: 96.12, y: 126.69), controlPoint1: NSPoint(x: 96.13, y: 126.71), controlPoint2: NSPoint(x: 96.12, y: 126.7))
        bezier7Path.line(to: NSPoint(x: 96.12, y: 121.06))
        bezier7Path.curve(to: NSPoint(x: 96.44, y: 120.75), controlPoint1: NSPoint(x: 96.12, y: 120.89), controlPoint2: NSPoint(x: 96.27, y: 120.75))
        bezier7Path.line(to: NSPoint(x: 104.56, y: 120.75))
        bezier7Path.curve(to: NSPoint(x: 104.88, y: 121.06), controlPoint1: NSPoint(x: 104.73, y: 120.75), controlPoint2: NSPoint(x: 104.88, y: 120.89))
        bezier7Path.line(to: NSPoint(x: 104.88, y: 126.69))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 100.15, y: 128.88))
        bezier7Path.line(to: NSPoint(x: 100.85, y: 128.88))
        bezier7Path.line(to: NSPoint(x: 101.09, y: 127))
        bezier7Path.line(to: NSPoint(x: 99.92, y: 127))
        bezier7Path.line(to: NSPoint(x: 100.15, y: 128.88))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 99.25, y: 121.38))
        bezier7Path.line(to: NSPoint(x: 96.75, y: 121.38))
        bezier7Path.line(to: NSPoint(x: 96.75, y: 126.38))
        bezier7Path.line(to: NSPoint(x: 99.25, y: 126.38))
        bezier7Path.line(to: NSPoint(x: 99.25, y: 121.38))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 99.29, y: 127))
        bezier7Path.line(to: NSPoint(x: 97.06, y: 127))
        bezier7Path.line(to: NSPoint(x: 98.47, y: 128.88))
        bezier7Path.line(to: NSPoint(x: 99.52, y: 128.88))
        bezier7Path.line(to: NSPoint(x: 99.29, y: 127))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 101.12, y: 121.38))
        bezier7Path.line(to: NSPoint(x: 99.88, y: 121.38))
        bezier7Path.line(to: NSPoint(x: 99.87, y: 126.38))
        bezier7Path.line(to: NSPoint(x: 101.12, y: 126.38))
        bezier7Path.line(to: NSPoint(x: 101.12, y: 121.38))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 101.48, y: 128.88))
        bezier7Path.line(to: NSPoint(x: 102.53, y: 128.88))
        bezier7Path.line(to: NSPoint(x: 103.94, y: 127))
        bezier7Path.line(to: NSPoint(x: 101.71, y: 127))
        bezier7Path.line(to: NSPoint(x: 101.48, y: 128.88))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 104.25, y: 121.38))
        bezier7Path.line(to: NSPoint(x: 101.75, y: 121.38))
        bezier7Path.line(to: NSPoint(x: 101.75, y: 126.38))
        bezier7Path.line(to: NSPoint(x: 104.25, y: 126.38))
        bezier7Path.line(to: NSPoint(x: 104.25, y: 121.38))
        bezier7Path.close()
        bezier7Path.move(to: NSPoint(x: 107.69, y: 120.12))
        bezier7Path.curve(to: NSPoint(x: 107.38, y: 119.81), controlPoint1: NSPoint(x: 107.52, y: 120.12), controlPoint2: NSPoint(x: 107.38, y: 119.98))
        bezier7Path.line(to: NSPoint(x: 107.38, y: 118.07))
        bezier7Path.line(to: NSPoint(x: 105.41, y: 120.03))
        bezier7Path.curve(to: NSPoint(x: 104.97, y: 120.03), controlPoint1: NSPoint(x: 105.29, y: 120.16), controlPoint2: NSPoint(x: 105.09, y: 120.16))
        bezier7Path.curve(to: NSPoint(x: 104.97, y: 119.59), controlPoint1: NSPoint(x: 104.84, y: 119.91), controlPoint2: NSPoint(x: 104.84, y: 119.71))
        bezier7Path.line(to: NSPoint(x: 106.93, y: 117.62))
        bezier7Path.line(to: NSPoint(x: 105.19, y: 117.62))
        bezier7Path.curve(to: NSPoint(x: 104.88, y: 117.31), controlPoint1: NSPoint(x: 105.02, y: 117.62), controlPoint2: NSPoint(x: 104.88, y: 117.48))
        bezier7Path.curve(to: NSPoint(x: 105.19, y: 117), controlPoint1: NSPoint(x: 104.88, y: 117.14), controlPoint2: NSPoint(x: 105.02, y: 117))
        bezier7Path.line(to: NSPoint(x: 107.69, y: 117))
        bezier7Path.curve(to: NSPoint(x: 107.81, y: 117.02), controlPoint1: NSPoint(x: 107.73, y: 117), controlPoint2: NSPoint(x: 107.77, y: 117.01))
        bezier7Path.curve(to: NSPoint(x: 107.9, y: 117.09), controlPoint1: NSPoint(x: 107.84, y: 117.04), controlPoint2: NSPoint(x: 107.87, y: 117.06))
        bezier7Path.curve(to: NSPoint(x: 107.91, y: 117.09), controlPoint1: NSPoint(x: 107.9, y: 117.09), controlPoint2: NSPoint(x: 107.91, y: 117.09))
        bezier7Path.curve(to: NSPoint(x: 107.98, y: 117.19), controlPoint1: NSPoint(x: 107.94, y: 117.12), controlPoint2: NSPoint(x: 107.96, y: 117.16))
        bezier7Path.curve(to: NSPoint(x: 107.99, y: 117.26), controlPoint1: NSPoint(x: 107.98, y: 117.22), controlPoint2: NSPoint(x: 107.99, y: 117.24))
        bezier7Path.curve(to: NSPoint(x: 108, y: 117.31), controlPoint1: NSPoint(x: 107.99, y: 117.28), controlPoint2: NSPoint(x: 108, y: 117.29))
        bezier7Path.line(to: NSPoint(x: 108, y: 119.81))
        bezier7Path.curve(to: NSPoint(x: 107.69, y: 120.12), controlPoint1: NSPoint(x: 108, y: 119.98), controlPoint2: NSPoint(x: 107.86, y: 120.12))
        bezier7Path.close()
        fillColor5.setFill()
        bezier7Path.fill()


        context.endTransparencyLayer()
        NSGraphicsContext.restoreGraphicsState()


        //// Pointer
        NSGraphicsContext.saveGraphicsState()
        context.translateBy(x: 99.5, y: 100.5)
        context.rotate(by: volumeValue * CGFloat.pi/180)

        context.setShadow(offset: NSSize(width: shadow.shadowOffset.width * resizedShadowScale, height: shadow.shadowOffset.height * resizedShadowScale), blur: shadow.shadowBlurRadius * resizedShadowScale, color: shadow.shadowColor!.cgColor)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier 4 Drawing
        let bezier4Path = NSBezierPath()
        bezier4Path.move(to: NSPoint(x: 0.5, y: -0.5))
        bezier4Path.line(to: NSPoint(x: -32.5, y: -37.5))
        strokeColor5.setStroke()
        bezier4Path.lineWidth = 8
        bezier4Path.miterLimit = 4
        bezier4Path.lineCapStyle = .round
        bezier4Path.stroke()


        //// Oval 2 Drawing
        let oval2Path = NSBezierPath(ovalIn: NSRect(x: -7.5, y: -7.5, width: 15, height: 15))
        fillColor3.setFill()
        oval2Path.fill()


        context.endTransparencyLayer()

        NSGraphicsContext.restoreGraphicsState()
        
        NSGraphicsContext.restoreGraphicsState()

    }

    @objc dynamic public class func drawTemperature(frame targetFrame: NSRect = NSRect(x: 0, y: 0, width: 200, height: 200), resizing: ResizingBehavior = .aspectFit, temperatureValue: CGFloat = 0) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext
        
        //// Resize to Target Frame
        NSGraphicsContext.saveGraphicsState()
        let resizedFrame: NSRect = resizing.apply(rect: NSRect(x: 0, y: 0, width: 200, height: 200), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 200, y: resizedFrame.height / 200)
        let resizedShadowScale: CGFloat = min(resizedFrame.width / 200, resizedFrame.height / 200)


        //// Color Declarations
        let strokeColor5 = NSColor(red: 1, green: 1, blue: 1, alpha: 1)
        let fillColor3 = NSColor(red: 0.969, green: 0.969, blue: 0.969, alpha: 1)
        let strokeColor8 = NSColor(red: 0.286, green: 0.318, blue: 0.349, alpha: 1)
        let fillColor4 = NSColor(red: 0.886, green: 0.886, blue: 0.886, alpha: 1)
        let strokeColor9 = NSColor(red: 0.984, green: 0.733, blue: 0.082, alpha: 0.5)
        let strokeColor10 = NSColor(red: 0.173, green: 0.761, blue: 0.408, alpha: 0.5)
        let strokeColor11 = NSColor(red: 0.984, green: 0.082, blue: 0.082, alpha: 0.6)
        let fillColor5 = NSColor(red: 0.2, green: 0.2, blue: 0.2, alpha: 1)

        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = NSColor.black.withAlphaComponent(0.1)
        shadow.shadowOffset = NSSize(width: 3, height: -3)
        shadow.shadowBlurRadius = 5

        //// Temperature Gauge
        //// Oval Drawing
        let ovalPath = NSBezierPath(ovalIn: NSRect(x: 30, y: 30, width: 140, height: 140))
        fillColor4.setFill()
        ovalPath.fill()
        strokeColor8.setStroke()
        ovalPath.lineWidth = 10
        ovalPath.stroke()


        //// Bezier Drawing
        let bezierPath = NSBezierPath()
        bezierPath.move(to: NSPoint(x: 68.63, y: 58.74))
        bezierPath.curve(to: NSPoint(x: 50.49, y: 84.63), controlPoint1: NSPoint(x: 60.04, y: 65.28), controlPoint2: NSPoint(x: 53.7, y: 74.33))
        bezierPath.curve(to: NSPoint(x: 50.69, y: 116.25), controlPoint1: NSPoint(x: 47.27, y: 94.93), controlPoint2: NSPoint(x: 47.34, y: 105.98))
        bezierPath.curve(to: NSPoint(x: 69.17, y: 141.9), controlPoint1: NSPoint(x: 54.04, y: 126.51), controlPoint2: NSPoint(x: 60.5, y: 135.47))
        bezierPath.curve(to: NSPoint(x: 99.1, y: 152.11), controlPoint1: NSPoint(x: 77.85, y: 148.33), controlPoint2: NSPoint(x: 88.3, y: 151.89))
        bezierPath.curve(to: NSPoint(x: 129.4, y: 143.09), controlPoint1: NSPoint(x: 109.89, y: 152.32), controlPoint2: NSPoint(x: 120.48, y: 149.17))
        bezierPath.curve(to: NSPoint(x: 148.89, y: 118.2), controlPoint1: NSPoint(x: 138.32, y: 137.02), controlPoint2: NSPoint(x: 145.13, y: 128.32))
        bezierPath.curve(to: NSPoint(x: 150.34, y: 86.61), controlPoint1: NSPoint(x: 152.64, y: 108.07), controlPoint2: NSPoint(x: 153.15, y: 97.04))
        bezierPath.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.9))
        strokeColor9.setStroke()
        bezierPath.lineWidth = 10
        bezierPath.miterLimit = 4
        bezierPath.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = NSBezierPath()
        bezier2Path.move(to: NSPoint(x: 50.49, y: 84.63))
        bezier2Path.curve(to: NSPoint(x: 50.69, y: 116.25), controlPoint1: NSPoint(x: 47.27, y: 94.93), controlPoint2: NSPoint(x: 47.34, y: 105.98))
        bezier2Path.curve(to: NSPoint(x: 69.17, y: 141.9), controlPoint1: NSPoint(x: 54.04, y: 126.51), controlPoint2: NSPoint(x: 60.5, y: 135.47))
        bezier2Path.curve(to: NSPoint(x: 99.1, y: 152.11), controlPoint1: NSPoint(x: 77.85, y: 148.33), controlPoint2: NSPoint(x: 88.3, y: 151.89))
        bezier2Path.curve(to: NSPoint(x: 129.4, y: 143.09), controlPoint1: NSPoint(x: 109.89, y: 152.32), controlPoint2: NSPoint(x: 120.48, y: 149.17))
        bezier2Path.curve(to: NSPoint(x: 148.88, y: 118.2), controlPoint1: NSPoint(x: 138.32, y: 137.02), controlPoint2: NSPoint(x: 145.13, y: 128.32))
        bezier2Path.curve(to: NSPoint(x: 150.34, y: 86.61), controlPoint1: NSPoint(x: 152.64, y: 108.07), controlPoint2: NSPoint(x: 153.15, y: 97.04))
        bezier2Path.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.9))
        strokeColor10.setStroke()
        bezier2Path.lineWidth = 10
        bezier2Path.miterLimit = 4
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = NSBezierPath()
        bezier3Path.move(to: NSPoint(x: 150.34, y: 86.61))
        bezier3Path.curve(to: NSPoint(x: 133.24, y: 60.02), controlPoint1: NSPoint(x: 147.54, y: 76.19), controlPoint2: NSPoint(x: 141.56, y: 66.89))
        strokeColor11.setStroke()
        bezier3Path.lineWidth = 10
        bezier3Path.miterLimit = 4
        bezier3Path.stroke()


        //// Group 2
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.7)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier 5 Drawing
        let bezier5Path = NSBezierPath()
        bezier5Path.move(to: NSPoint(x: 99.94, y: 67.64))
        bezier5Path.line(to: NSPoint(x: 101.72, y: 67.64))
        bezier5Path.line(to: NSPoint(x: 101.72, y: 64.08))
        bezier5Path.line(to: NSPoint(x: 105.05, y: 67.64))
        bezier5Path.line(to: NSPoint(x: 107.38, y: 67.64))
        bezier5Path.line(to: NSPoint(x: 103.85, y: 64.08))
        bezier5Path.line(to: NSPoint(x: 107.57, y: 59))
        bezier5Path.line(to: NSPoint(x: 105.25, y: 59))
        bezier5Path.line(to: NSPoint(x: 102.58, y: 62.77))
        bezier5Path.line(to: NSPoint(x: 101.72, y: 61.89))
        bezier5Path.line(to: NSPoint(x: 101.72, y: 59))
        bezier5Path.line(to: NSPoint(x: 99.94, y: 59))
        bezier5Path.line(to: NSPoint(x: 99.94, y: 67.64))
        bezier5Path.close()
        fillColor5.setFill()
        bezier5Path.fill()


        context.endTransparencyLayer()
        NSGraphicsContext.restoreGraphicsState()


        //// Group 3
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.5)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier 6 Drawing
        let bezier6Path = NSBezierPath()
        bezier6Path.move(to: NSPoint(x: 104.06, y: 120))
        bezier6Path.curve(to: NSPoint(x: 103.96, y: 120.02), controlPoint1: NSPoint(x: 104.03, y: 120), controlPoint2: NSPoint(x: 103.99, y: 120.01))
        bezier6Path.line(to: NSPoint(x: 95.21, y: 123.14))
        bezier6Path.curve(to: NSPoint(x: 95.02, y: 123.54), controlPoint1: NSPoint(x: 95.05, y: 123.2), controlPoint2: NSPoint(x: 94.96, y: 123.38))
        bezier6Path.line(to: NSPoint(x: 95.64, y: 125.41))
        bezier6Path.curve(to: NSPoint(x: 95.8, y: 125.59), controlPoint1: NSPoint(x: 95.67, y: 125.49), controlPoint2: NSPoint(x: 95.73, y: 125.56))
        bezier6Path.curve(to: NSPoint(x: 96.04, y: 125.61), controlPoint1: NSPoint(x: 95.88, y: 125.63), controlPoint2: NSPoint(x: 95.96, y: 125.64))
        bezier6Path.line(to: NSPoint(x: 104.79, y: 122.48))
        bezier6Path.curve(to: NSPoint(x: 104.98, y: 122.09), controlPoint1: NSPoint(x: 104.95, y: 122.43), controlPoint2: NSPoint(x: 105.04, y: 122.25))
        bezier6Path.line(to: NSPoint(x: 104.36, y: 120.21))
        bezier6Path.curve(to: NSPoint(x: 104.2, y: 120.03), controlPoint1: NSPoint(x: 104.33, y: 120.13), controlPoint2: NSPoint(x: 104.28, y: 120.07))
        bezier6Path.curve(to: NSPoint(x: 104.06, y: 120), controlPoint1: NSPoint(x: 104.16, y: 120.01), controlPoint2: NSPoint(x: 104.11, y: 120))
        bezier6Path.close()
        bezier6Path.move(to: NSPoint(x: 95.71, y: 123.63))
        bezier6Path.line(to: NSPoint(x: 103.87, y: 120.71))
        bezier6Path.line(to: NSPoint(x: 104.3, y: 122))
        bezier6Path.line(to: NSPoint(x: 96.13, y: 124.91))
        bezier6Path.line(to: NSPoint(x: 95.71, y: 123.63))
        bezier6Path.close()
        fillColor5.setFill()
        bezier6Path.fill()


        //// Bezier 7 Drawing
        let bezier7Path = NSBezierPath()
        bezier7Path.move(to: NSPoint(x: 95.94, y: 120))
        bezier7Path.curve(to: NSPoint(x: 95.81, y: 120.03), controlPoint1: NSPoint(x: 95.89, y: 120), controlPoint2: NSPoint(x: 95.85, y: 120.01))
        bezier7Path.curve(to: NSPoint(x: 95.64, y: 120.21), controlPoint1: NSPoint(x: 95.73, y: 120.06), controlPoint2: NSPoint(x: 95.67, y: 120.13))
        bezier7Path.line(to: NSPoint(x: 95.02, y: 122.09))
        bezier7Path.curve(to: NSPoint(x: 95.2, y: 122.48), controlPoint1: NSPoint(x: 94.96, y: 122.25), controlPoint2: NSPoint(x: 95.04, y: 122.42))
        bezier7Path.line(to: NSPoint(x: 96.76, y: 123.1))
        bezier7Path.curve(to: NSPoint(x: 97.17, y: 122.93), controlPoint1: NSPoint(x: 96.92, y: 123.17), controlPoint2: NSPoint(x: 97.1, y: 123.09))
        bezier7Path.curve(to: NSPoint(x: 96.99, y: 122.52), controlPoint1: NSPoint(x: 97.23, y: 122.77), controlPoint2: NSPoint(x: 97.15, y: 122.59))
        bezier7Path.line(to: NSPoint(x: 95.7, y: 122.01))
        bezier7Path.line(to: NSPoint(x: 96.13, y: 120.73))
        bezier7Path.line(to: NSPoint(x: 99.57, y: 122.16))
        bezier7Path.curve(to: NSPoint(x: 99.98, y: 122), controlPoint1: NSPoint(x: 99.73, y: 122.23), controlPoint2: NSPoint(x: 99.91, y: 122.16))
        bezier7Path.curve(to: NSPoint(x: 99.81, y: 121.59), controlPoint1: NSPoint(x: 100.04, y: 121.84), controlPoint2: NSPoint(x: 99.97, y: 121.65))
        bezier7Path.line(to: NSPoint(x: 96.06, y: 120.02))
        bezier7Path.curve(to: NSPoint(x: 95.94, y: 120), controlPoint1: NSPoint(x: 96.02, y: 120.01), controlPoint2: NSPoint(x: 95.98, y: 120))
        bezier7Path.close()
        fillColor5.setFill()
        bezier7Path.fill()


        //// Bezier 8 Drawing
        let bezier8Path = NSBezierPath()
        bezier8Path.move(to: NSPoint(x: 103.13, y: 122.5))
        bezier8Path.curve(to: NSPoint(x: 102.84, y: 122.7), controlPoint1: NSPoint(x: 103, y: 122.5), controlPoint2: NSPoint(x: 102.88, y: 122.57))
        bezier8Path.curve(to: NSPoint(x: 103.01, y: 123.1), controlPoint1: NSPoint(x: 102.77, y: 122.86), controlPoint2: NSPoint(x: 102.85, y: 123.04))
        bezier8Path.line(to: NSPoint(x: 104.3, y: 123.62))
        bezier8Path.line(to: NSPoint(x: 103.87, y: 124.89))
        bezier8Path.line(to: NSPoint(x: 100.43, y: 123.46))
        bezier8Path.curve(to: NSPoint(x: 100.02, y: 123.63), controlPoint1: NSPoint(x: 100.27, y: 123.39), controlPoint2: NSPoint(x: 100.09, y: 123.47))
        bezier8Path.curve(to: NSPoint(x: 100.19, y: 124.04), controlPoint1: NSPoint(x: 99.96, y: 123.79), controlPoint2: NSPoint(x: 100.03, y: 123.97))
        bezier8Path.line(to: NSPoint(x: 103.94, y: 125.6))
        bezier8Path.curve(to: NSPoint(x: 104.19, y: 125.6), controlPoint1: NSPoint(x: 104.02, y: 125.63), controlPoint2: NSPoint(x: 104.11, y: 125.63))
        bezier8Path.curve(to: NSPoint(x: 104.36, y: 125.41), controlPoint1: NSPoint(x: 104.27, y: 125.56), controlPoint2: NSPoint(x: 104.33, y: 125.49))
        bezier8Path.line(to: NSPoint(x: 104.98, y: 123.54))
        bezier8Path.curve(to: NSPoint(x: 104.8, y: 123.15), controlPoint1: NSPoint(x: 105.04, y: 123.38), controlPoint2: NSPoint(x: 104.96, y: 123.21))
        bezier8Path.line(to: NSPoint(x: 103.24, y: 122.52))
        bezier8Path.curve(to: NSPoint(x: 103.13, y: 122.5), controlPoint1: NSPoint(x: 103.2, y: 122.51), controlPoint2: NSPoint(x: 103.16, y: 122.5))
        bezier8Path.close()
        fillColor5.setFill()
        bezier8Path.fill()


        //// Bezier 9 Drawing
        let bezier9Path = NSBezierPath()
        bezier9Path.move(to: NSPoint(x: 98.86, y: 125.7))
        bezier9Path.curve(to: NSPoint(x: 98.81, y: 125.7), controlPoint1: NSPoint(x: 98.84, y: 125.7), controlPoint2: NSPoint(x: 98.83, y: 125.7))
        bezier9Path.curve(to: NSPoint(x: 96.25, y: 127.88), controlPoint1: NSPoint(x: 97.21, y: 125.96), controlPoint2: NSPoint(x: 96.25, y: 126.77))
        bezier9Path.curve(to: NSPoint(x: 98.45, y: 131.34), controlPoint1: NSPoint(x: 96.25, y: 129.31), controlPoint2: NSPoint(x: 97.42, y: 130.39))
        bezier9Path.curve(to: NSPoint(x: 100, y: 133.44), controlPoint1: NSPoint(x: 99.25, y: 132.08), controlPoint2: NSPoint(x: 100, y: 132.77))
        bezier9Path.line(to: NSPoint(x: 100, y: 134.69))
        bezier9Path.curve(to: NSPoint(x: 100.17, y: 134.97), controlPoint1: NSPoint(x: 100, y: 134.81), controlPoint2: NSPoint(x: 100.07, y: 134.91))
        bezier9Path.curve(to: NSPoint(x: 100.5, y: 134.94), controlPoint1: NSPoint(x: 100.28, y: 135.02), controlPoint2: NSPoint(x: 100.4, y: 135.01))
        bezier9Path.curve(to: NSPoint(x: 104.38, y: 128.86), controlPoint1: NSPoint(x: 100.66, y: 134.82), controlPoint2: NSPoint(x: 104.38, y: 132.06))
        bezier9Path.curve(to: NSPoint(x: 100.84, y: 125.71), controlPoint1: NSPoint(x: 104.38, y: 126.93), controlPoint2: NSPoint(x: 102.55, y: 125.97))
        bezier9Path.curve(to: NSPoint(x: 100.49, y: 125.95), controlPoint1: NSPoint(x: 100.68, y: 125.68), controlPoint2: NSPoint(x: 100.52, y: 125.79))
        bezier9Path.line(to: NSPoint(x: 100.17, y: 127.58))
        bezier9Path.line(to: NSPoint(x: 99.13, y: 125.85))
        bezier9Path.curve(to: NSPoint(x: 98.86, y: 125.7), controlPoint1: NSPoint(x: 99.07, y: 125.76), controlPoint2: NSPoint(x: 98.97, y: 125.7))
        bezier9Path.close()
        bezier9Path.move(to: NSPoint(x: 100.63, y: 134.03))
        bezier9Path.line(to: NSPoint(x: 100.63, y: 133.44))
        bezier9Path.curve(to: NSPoint(x: 98.87, y: 130.88), controlPoint1: NSPoint(x: 100.63, y: 132.5), controlPoint2: NSPoint(x: 99.77, y: 131.71))
        bezier9Path.curve(to: NSPoint(x: 96.88, y: 127.88), controlPoint1: NSPoint(x: 97.89, y: 129.97), controlPoint2: NSPoint(x: 96.88, y: 129.04))
        bezier9Path.curve(to: NSPoint(x: 98.7, y: 126.36), controlPoint1: NSPoint(x: 96.88, y: 126.87), controlPoint2: NSPoint(x: 98.09, y: 126.49))
        bezier9Path.line(to: NSPoint(x: 100.04, y: 128.6))
        bezier9Path.curve(to: NSPoint(x: 100.37, y: 128.75), controlPoint1: NSPoint(x: 100.11, y: 128.71), controlPoint2: NSPoint(x: 100.24, y: 128.77))
        bezier9Path.curve(to: NSPoint(x: 100.62, y: 128.5), controlPoint1: NSPoint(x: 100.49, y: 128.72), controlPoint2: NSPoint(x: 100.59, y: 128.63))
        bezier9Path.line(to: NSPoint(x: 101.04, y: 126.38))
        bezier9Path.curve(to: NSPoint(x: 103.75, y: 128.86), controlPoint1: NSPoint(x: 102.4, y: 126.65), controlPoint2: NSPoint(x: 103.75, y: 127.43))
        bezier9Path.curve(to: NSPoint(x: 100.63, y: 134.03), controlPoint1: NSPoint(x: 103.75, y: 131.08), controlPoint2: NSPoint(x: 101.62, y: 133.18))
        bezier9Path.close()
        fillColor5.setFill()
        bezier9Path.fill()


        context.endTransparencyLayer()
        NSGraphicsContext.restoreGraphicsState()


        //// Pointer
        NSGraphicsContext.saveGraphicsState()
        context.translateBy(x: 99.5, y: 100.5)
        context.rotate(by: temperatureValue * CGFloat.pi/180)

        context.setShadow(offset: NSSize(width: shadow.shadowOffset.width * resizedShadowScale, height: shadow.shadowOffset.height * resizedShadowScale), blur: shadow.shadowBlurRadius * resizedShadowScale, color: shadow.shadowColor!.cgColor)
        context.beginTransparencyLayer(auxiliaryInfo: nil)


        //// Bezier 4 Drawing
        let bezier4Path = NSBezierPath()
        bezier4Path.move(to: NSPoint(x: 0.5, y: -0.5))
        bezier4Path.line(to: NSPoint(x: -32.5, y: -37.5))
        strokeColor5.setStroke()
        bezier4Path.lineWidth = 8
        bezier4Path.miterLimit = 4
        bezier4Path.lineCapStyle = .round
        bezier4Path.stroke()


        //// Oval 2 Drawing
        let oval2Path = NSBezierPath(ovalIn: NSRect(x: -7.5, y: -7.5, width: 15, height: 15))
        fillColor3.setFill()
        oval2Path.fill()


        context.endTransparencyLayer()

        NSGraphicsContext.restoreGraphicsState()
        
        NSGraphicsContext.restoreGraphicsState()

    }




    @objc(GaugesResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: NSRect, target: NSRect) -> NSRect {
            if rect == target || target == NSRect.zero {
                return rect
            }

            var scales = NSSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
